version: '3'
services:
  api:
    build:
      context: ./
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=starter
    volumes:
      - './dist:/app/dist/'
    ports:
      - "5001:3000"
    depends_on:
      - "db"
    networks:
      - webnet
  db:
    image: postgres:9.6
    environment:
      - POSTGRES_DB=starter
      - POSTGRES_USER=postgres
    volumes:
      - "./data/postgres:/var/lib/postgresql/data"
    ports:
      - 9876:5432
    networks:
      - webnet
networks:
  webnet:
    driver: bridge
